# Generated by Django 2.2.16 on 2022-06-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
